#!/usr/bin/osascript

#**********************************************************************
# Copyright 2020 Advanced Micro Devices, Inc
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#********************************************************************


do shell script "/Users/Shared/RadeonProRender/Blender/addon/checker"

tell me to activate
set pwrd to the text returned of (display dialog "Registration key:" default answer "")
if (pwrd is not equal to "TagYourRenders#ProRender") then
display dialog "Invalid key entered: cancelling installation." buttons {"OK" } default button 1
    error "Incorrect key entered"
end if
