#!/usr/bin/python

from __future__ import print_function
import os
import sys
import subprocess
import shutil

loggingOn = False

def log(str):
    if loggingOn:
        f = open("/tmp/uninstall-log.txt","a")
        f.write(str)
        f.close()

log("UNINSTALL script started\n")

blender_path = None

home = os.path.expanduser("~")

def ascript_get_blender_distro():
    cmd = """osascript<<END
    tell app "Finder"
    activate
    set folderpath to choose folder with prompt "Please select the Blender installation directory"
    set posix_folderpath to (the POSIX path of folderpath)
    end tell
    return posix_folderpath
    END"""

    output = subprocess.check_output(cmd,shell=True)
    return output;

def ascript_error(str):
    cmd = """osascript<<END
    tell me to activate
    display dialog "Installation error: %s" buttons {"OK"} default button 1
    END"""

    fullcmd = (cmd % str)
    output = subprocess.check_output(fullcmd,shell=True)
    return output


# 1. Get blender distro and install the plugin
#

log("UNINSTALL script getting blender distro\n")

try:
    result = ascript_get_blender_distro()
except:
    sys.exit(-1)

blender_path = result.strip()

blender_executable_path = str(blender_path) + str("/blender.app/Contents/MacOS/blender")
if not os.path.exists(blender_executable_path):
    ascript_error("Could not find the .../blender.app/Contents/MacOS/blender executable")
    sys.exit(-1)

install_to_blender = str("/Users/Shared/RadeonProRender/Blender/addon/remove_blender_addon.py")

install_blender_addon_cmd = [
                str(blender_executable_path), '--background',
                '--python', str(install_to_blender)]

log("cmd: '%s'\n"% install_blender_addon_cmd)

output=""
try:
    output=subprocess.check_output(install_blender_addon_cmd, stderr=subprocess.PIPE)
except subprocess.CalledProcessError as e:
    print("Blender ouput: %s", e.output.decode('utf8'))
    sys.exit(-1)

log("output: '%s'\n"% output)

# 2. Return
#

log("UNINSTALL script done -----------------------------------\n")

sys.exit(0)
